apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ app.name }}"
  labels:
    app: "{{ app.name }}"
  namespace: default
spec:
  minReadySeconds: 20
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      app: "{{ app.name }}"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "{{ app.name }}"
    spec:
      priorityClassName: high-priority
      containers:
      - image: "{{ image.url }}"
        imagePullPolicy: Always
        name: "{{ app.name }}"
        resources:
          requests:
            cpu: {{ resources and resources.requests and resources.requests.cpu or 1 }}
            memory: {{ resources and resources.requests and resources.requests.memory or '800Mi' }}
          limits:
            cpu: {{ resources and resources.limits and resources.limits.cpu or 1.5 }}
            memory: {{ resources and resources.limits and resources.limits.memory or '1000Mi' }}
        ports:
          - name: api-port
            containerPort: {{ app.port or 8081 }}
            protocol: "{{ app.protocol or 'TCP' }}"
      {% if container %}
      {% set envFromSecret = container.envFromSecret or {} %}
      {% set envFromConfig = container.envFromConfig or {} %}
      {% set envRaw = container.env or {} %}
      {% if envFromConfig|length + envRaw|length + envFromSecret|length > 0 %}
        env:
        {% for key, value in envRaw.items() %}
          - name: {{ key }}
            value: {{ value }}
        {% endfor %}
        {% for key, values in envFromConfig.items() %}
        {% set FILE_NAME = app.name + '-config' if key == 'self' else key %}
        {% for value in values %}
          - name: {{ value }}
            valueFrom:
              configMapKeyRef:
                name: {{ FILE_NAME }}
                key: {{ value }}
        {% endfor %}
        {% endfor %}
        {% for key, values in envFromSecret.items() %}
        {% set FILE_NAME = app.name + '-secret' if key == 'self' else key %}
        {% for value in values %}
          - name: {{ value }}
            valueFrom:
              secretKeyRef:
                name: {{ FILE_NAME }}
                key: {{ value }}
        {% endfor %}
        {% endfor %}
      {% endif %}
      {% if container.readinessProbe %}
        readinessProbe:
          httpGet:
            path: {{ container.healthCheckUrl or '/current/health' }}
            port: api-port
            httpHeaders:
              - name: "{{ container.readinessProbe.httpHeaderName }}"
                value: readiness
          failureThreshold: {{ container.readinessProbe.failureThreshold or 2 }}
          timeoutSeconds: {{ container.readinessProbe.timeoutSeconds or 2 }}
          periodSeconds: {{ container.readinessProbe.periodSeconds or 20 }}
          initialDelaySeconds: {{ container.readinessProbe.initialDelaySeconds or 15 }}
      {% endif %}
      {% if container.readinessProbe %}
        livenessProbe:
          httpGet:
            path: {{ container.healthCheckUrl or '/current/health' }}
            port: api-port
            httpHeaders:
              - name: "{{ container.livenessProbe.httpHeaderName }}"
                value: liveness
          failureThreshold: {{ container.livenessProbe.failureThreshold or 2 }}
          timeoutSeconds: {{ container.livenessProbe.timeoutSeconds or 2 }}
          periodSeconds: {{ container.livenessProbe.periodSeconds or 20 }}
          initialDelaySeconds: {{ container.livenessProbe.initialDelaySeconds or 15 }}
      {% endif %}
      {% endif %}

