apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ name }}"
spec:
  schedule: "{{ schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: "{{ name }}"
              image: "{{ image }}"
              imagePullPolicy: IfNotPresent
              restartPolicy: Never