apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: {{ cluster.certificate }}
      server: {{ cluster.server }}
    name: {{ cluster.alias }}
contexts:
- context:
    cluster: {{ cluster.alias }}
    user: {{ cluster.user }}
  name: {{ cluster.ctx }}
current-context: {{ cluster.ctx }}
kind: Config
preferences: {}
users:
- name: {{ cluster.user }}
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - {{ cluster.name or cluster.alias }}
      command: aws-iam-authenticator
      env: null
